# This YAML file defines the "Green" deployment for the Django messaging app.
# This represents the new version that will be deployed alongside the Blue version.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
  labels:
    app: messaging-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: green
  template:
    metadata:
      labels:
        app: messaging-app
        version: green
    spec:
      containers:
      - name: messaging-app-container
        # IMPORTANT: Replace with the image for your new application version (e.g., v2.0)
        image: your-dockerhub-username/messaging-app:v2.0
        ports:
        - containerPort: 8000
