from django.urls import path, include
from rest_framework import routers
from .views import ConversationViewSet, MessageViewSet

# Create a router instance to automatically generate URL patterns for viewsets.
router = routers.DefaultRouter()

# Register ConversationViewSet with the router.
# This will create URLs like:
# /conversations/ (list/create conversations)
# /conversations/{pk}/ (retrieve/update/delete specific conversation)
# /conversations/{pk}/messages/ (list messages for a specific conversation)
# /conversations/{pk}/send_message/ (send a message to a specific conversation)
router.register(r'conversations', ConversationViewSet, basename='conversation')

# Register MessageViewSet with the router.
# This will create URLs like:
# /messages/ (list messages)
# /messages/{pk}/ (retrieve specific message)
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    # Include all the URLs generated by the router.
    path('', include(router.urls)),
]
