from django.urls import path, include # Ensure path and include are imported
from rest_framework import routers # Import routers
from .views import ConversationViewSet, MessageViewSet

# Create a router instance to automatically generate URL patterns for viewsets.
# Use routers.DefaultRouter() as specified.
router = routers.DefaultRouter()

# Register ConversationViewSet with the router.
# This will create URLs like /conversations/, /conversations/{pk}/, etc.
router.register(r'conversations', ConversationViewSet, basename='conversation')

# Register MessageViewSet with the router.
# This will create URLs like /messages/, /messages/{pk}/ etc.
# While messages are often accessed via conversations, this provides a general endpoint.
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    # Include the URLs generated by the router.
    path('', include(router.urls)),
]
